name: Build and deploy Node.js app to Azure Web App - abastecimiento-milicic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Descarga directo tus archivos del repositorio (incluyendo los CSV nuevos)
      - uses: actions/checkout@v4

      # 2. Inicia sesión de forma segura en Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_302C4CBE3E7F4333B942F2EE236773B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23FA99BC3F474BE1825F03BA1F52D657 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04EB8574BF2946F99317A4D0EF0A17A3 }}

      # 3. Sube los archivos directo a producción sin compilar nada
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'abastecimiento-milicic'
          slot-name: 'Production'
          package: . # Sube la raíz directamente
          
